export const categories = [
  // PARENT CATEGORIES STARTS
  {
    id: 1,
    parentCategory: null,
    name: "Supermarkets",
    completeName: "Supermarkets",
    parentPath: "",
  },
  {
    id: 2,
    parentCategory: null,
    name: "Health & Beauty",
    completeName: "Health & Beauty",
    parentPath: "",
  },
  {
    id: 3,
    parentCategory: null,
    name: "Home & Office",
    completeName: "Home & Office",
    parentPath: "",
  },
  {
    id: 4,
    parentCategory: null,
    name: "Appliances",
    completeName: "Appliances",
    parentPath: "",
  },
  {
    id: 5,
    parentCategory: null,
    name: "Phones & Tablets",
    completeName: "Phones & Tablets",
    parentPath: "",
  },
  {
    id: 6,
    parentCategory: null,
    name: "Computing",
    completeName: "Computing",
    parentPath: "",
  },
  {
    id: 7,
    parentCategory: null,
    name: "Fashion",
    completeName: "Fashion",
    parentPath: "",
  },
  {
    id: 8,
    parentCategory: null,
    name: "Baby Products",
    completeName: "Baby Products",
    parentPath: "",
  },
  {
    id: 9,
    parentCategory: null,
    name: "Gaming",
    completeName: "Gaming",
    parentPath: "",
  },
  {
    id: 10,
    parentCategory: null,
    name: "Sports & Outdoor",
    completeName: "Sports & Outdoor",
    parentPath: "",
  },
  {
    id: 11,
    parentCategory: null,
    name: "Other Categories",
    completeName: "Other Categories",
    parentPath: "",
  },
  // PARENT CATEGORIES ENDS HERE

  // SUB CATEGORIES STARTS HERE
  {
    id: 12,
    parentCategory: 1,
    name: "Food Cupboard",
    completeName: "Supermarkets > Food Cupboard",
    parentPath: "Supermarkets",
  },
  {
    id: 13,
    parentCategory: 1,
    name: "Beverages",
    completeName: "Supermarkets > Beverages",
    parentPath: "Supermarkets",
  },
  {
    id: 14,
    parentCategory: 1,
    name: "Household Cleaning",
    completeName: "Supermarkets > Household Cleaning",
    parentPath: "Supermarkets",
  },
  {
    id: 15,
    parentCategory: 1,
    name: "Beer, Wine & Spirits",
    completeName: "Supermarkets > Beer, Wine & Spirits",
    parentPath: "Supermarkets",
  },
  {
    id: 16,
    parentCategory: 1,
    name: "Baby Products",
    completeName: "Supermarkets > Baby Products",
    parentPath: "Supermarkets",
  },
  {
    id: 17,
    parentCategory: 2,
    name: "Make Up",
    completeName: "Health & Beauty > Make Up",
    parentPath: "Health & Beauty",
  },
  {
    id: 18,
    parentCategory: 2,
    name: "Personal Care",
    completeName: "Health & Beauty > Personal Care",
    parentPath: "Health & Beauty",
  },
  {
    id: 19,
    parentCategory: 2,
    name: "Fragrances",
    completeName: "Health & Beauty > Fragrances",
    parentPath: "Health & Beauty",
  },
  {
    id: 20,
    parentCategory: 2,
    name: "Hair Care",
    completeName: "Health & Beauty > Hair Care",
    parentPath: "Health & Beauty",
  },
  {
    id: 21,
    parentCategory: 2,
    name: "Oral Care",
    completeName: "Health & Beauty > Oral Care",
    parentPath: "Health & Beauty",
  },
  {
    id: 22,
    parentCategory: 2,
    name: "Health Care",
    completeName: "Health & Beauty > Health Care",
    parentPath: "Health & Beauty",
  },
  {
    id: 23,
    parentCategory: 2,
    name: "Vitamins & Dietary Supplements",
    completeName: "Health & Beauty > Vitamins & Dietary Supplements",
    parentPath: "Health & Beauty",
  },
  {
    id: 24,
    parentCategory: 3,
    name: "Home & Kitchen",
    completeName: "Home & Office > Home & Kitchen",
    parentPath: "Home & Office",
  },
  {
    id: 25,
    parentCategory: 3,
    name: "Office Products",
    completeName: "Home & Office > Office Products",
    parentPath: "Home & Office",
  },
  {
    id: 26,
    parentCategory: 3,
    name: "Home & Office Furniture",
    completeName: "Home & Office > Home & Office Furniture",
    parentPath: "Home & Office",
  },
  {
    id: 27,
    parentCategory: 4,
    name: "Small Appliances",
    completeName: "Appliances > Small Appliances",
    parentPath: "Appliances",
  },
  {
    id: 28,
    parentCategory: 4,
    name: "Large Appliances",
    completeName: "Appliances > Large Appliances",
    parentPath: "Appliances",
  },
  {
    id: 30,
    parentCategory: 5,
    name: "Mobile Phones",
    completeName: "Phones & Tablets > Mobile Phones",
    parentPath: "Phones & Tablets",
  },
  {
    id: 31,
    parentCategory: 5,
    name: "Tablets",
    completeName: "Phones & Tablets > Tablets",
    parentPath: "Phones & Tablets",
  },
  {
    id: 32,
    parentCategory: 5,
    name: "Mobile Accessories",
    completeName: "Phones & Tablets > Mobile Accessories",
    parentPath: "Phones & Tablets",
  },
  {
    id: 33,
    parentCategory: 5,
    name: "Top Smart Phones",
    completeName: "Phones & Tablets > Top Smart Phones",
    parentPath: "Phones & Tablets",
  },
  {
    id: 34,
    parentCategory: 5,
    name: "Top Phone Brands",
    completeName: "Phones & Tablets > Top Phone Brands",
    parentPath: "Phones & Tablets",
  },
  {
    id: 35,
    parentCategory: 6,
    name: "Computers",
    completeName: "Computing > Computers",
    parentPath: "Computing",
  },
  {
    id: 36,
    parentCategory: 6,
    name: "Data Storage",
    completeName: "Computing > Data Storage",
    parentPath: "Computing",
  },
  {
    id: 37,
    parentCategory: 6,
    name: "Printers",
    completeName: "Computing > Printers",
    parentPath: "Computing",
  },
  {
    id: 38,
    parentCategory: 6,
    name: "Computer Accessories",
    completeName: "Computing > Computer Accessories",
    parentPath: "Computing",
  },
  {
    id: 39,
    parentCategory: 6,
    name: "Top Brands",
    completeName: "Computing > Top Brands",
    parentPath: "Computing",
  },
  {
    id: 40,
    parentCategory: 7,
    name: "Women's Fashion",
    completeName: "Fashion > Women's Fashion",
    parentPath: "Fashion",
  },
  {
    id: 41,
    parentCategory: 7,
    name: "Kid's Fashion",
    completeName: "Fashion > Kid's Fashion",
    parentPath: "Fashion",
  },
  {
    id: 42,
    parentCategory: 7,
    name: "Men's Fashion",
    completeName: "Fashion > Men's Fashion",
    parentPath: "Fashion",
  },
  {
    id: 43,
    parentCategory: 7,
    name: "Watches",
    completeName: "Fashion > Watches",
    parentPath: "Fashion",
  },
  {
    id: 44,
    parentCategory: 7,
    name: "Sunglasses",
    completeName: "Fashion > Sunglasses",
    parentPath: "Fashion",
  },
  {
    id: 45,
    parentCategory: 7,
    name: "Top Brands",
    completeName: "Fashion > Top Brands",
    parentPath: "Fashion",
  },
  {
    id: 46,
    parentCategory: 8,
    name: "Apparel & Accessories",
    completeName: "Baby Products > Apparel & Accessories",
    parentPath: "Baby Products",
  },
  {
    id: 47,
    parentCategory: 8,
    name: "Diapering",
    completeName: "Baby Products > Diapering",
    parentPath: "Baby Products",
  },
  {
    id: 48,
    parentCategory: 8,
    name: "Baby & Toddler Toys",
    completeName: "Baby Products > Baby & Toddler Toys",
    parentPath: "Baby Products",
  },
  {
    id: 49,
    parentCategory: 8,
    name: "Bathing & Skin Care",
    completeName: "Baby Products > Bathing & Skin Care",
    parentPath: "Baby Products",
  },
  {
    id: 50,
    parentCategory: 8,
    name: "Feeding",
    completeName: "Baby Products > Feeding",
    parentPath: "Baby Products",
  },
  {
    id: 51,
    parentCategory: 8,
    name: "Food Storage",
    completeName: "Baby Products > Food Storage",
    parentPath: "Baby Products",
  },
  {
    id: 52,
    parentCategory: 8,
    name: "Gear",
    completeName: "Baby Products > Gear",
    parentPath: "Baby Products",
  },
  {
    id: 53,
    parentCategory: 9,
    name: "Playstation",
    completeName: "Gaming > Playstation",
    parentPath: "Gaming",
  },
  {
    id: 54,
    parentCategory: 9,
    name: "XBox",
    completeName: "Gaming > XBox",
    parentPath: "Gaming",
  },
  {
    id: 55,
    parentCategory: 9,
    name: "Nintendo",
    completeName: "Gaming > Nintendo",
    parentPath: "Gaming",
  },
  {
    id: 56,
    parentCategory: 9,
    name: "Top Games",
    completeName: "Gaming > Top Games",
    parentPath: "Gaming",
  },
  {
    id: 57,
    parentCategory: 10,
    name: "Cardio Training",
    completeName: "Sports & Outdoor > Cardio Training",
    parentPath: "Sports & Outdoor",
  },
  {
    id: 58,
    parentCategory: 10,
    name: "Strength Training Equipment",
    completeName: "Sports & Outdoor > Strength Training Equipment",
    parentPath: "Sports & Outdoor",
  },
  {
    id: 59,
    parentCategory: 10,
    name: "Accessories",
    completeName: "Sports & Outdoor > Accessories",
    parentPath: "Sports & Outdoor",
  },
  {
    id: 60,
    parentCategory: 10,
    name: "Team Sports",
    completeName: "Sports & Outdoor > Team Sports",
    parentPath: "Sports & Outdoor",
  },
  {
    id: 61,
    parentCategory: 11,
    name: "Made in Aba",
    completeName: "Other Categories > Made in Aba",
    parentPath: "Other Categories",
  },
  {
    id: 62,
    parentCategory: 11,
    name: "Raw Materials",
    completeName: "Other Categories > Raw Materials",
    parentPath: "Other Categories",
  },
  {
    id: 63,
    parentCategory: 11,
    name: "Grocery",
    completeName: "Other Categories > Grocery",
    parentPath: "Other Categories",
  },

  // SUB CATEGORIES ENDS HERE
  {
    id: 64,
    parentCategory: 12,
    name: "Grains & Rice",
    completeName: "Supermarkets > Food Cupboard > Grains & Rice",
    parentPath: "Supermarkets > Food Cupboard",
  },
  {
    id: 65,
    parentCategory: 12,
    name: "Pasta & Noodles",
    completeName: "Supermarkets > Food Cupboard > Pasta & Noodles",
    parentPath: "Supermarkets > Food Cupboard",
  },
  {
    id: 66,
    parentCategory: 12,
    name: "Breakfast Foods",
    completeName: "Supermarkets > Food Cupboard > Breakfast Foods",
    parentPath: "Supermarkets > Food Cupboard",
  },
  {
    id: 67,
    parentCategory: 12,
    name: "Herbs, Spices & Seasoning",
    completeName: "Supermarkets > Food Cupboard > Herbs, Spices & Seasoning",
    parentPath: "Supermarkets > Food Cupboard",
  },
  {
    id: 68,
    parentCategory: 12,
    name: "Flours & Meals",
    completeName: "Supermarkets > Food Cupboard > Flours & Meals",
    parentPath: "Supermarkets > Food Cupboard",
  },
  {
    id: 69,
    parentCategory: 12,
    name: "Malt Drinks",
    completeName: "Supermarkets > Food Cupboard > Malt Drinks",
    parentPath: "Supermarkets > Food Cupboard",
  },
  {
    id: 70,
    parentCategory: 12,
    name: "Coffee",
    completeName: "Supermarkets > Food Cupboard > Coffee",
    parentPath: "Supermarkets > Food Cupboard",
  },
  {
    id: 71,
    parentCategory: 12,
    name: "Water",
    completeName: "Supermarkets > Food Cupboard > Water",
    parentPath: "Supermarkets > Food Cupboard",
  },
  {
    id: 72,
    parentCategory: 12,
    name: "Cooking Oil",
    completeName: "Supermarkets > Food Cupboard > Cooking Oil",
    parentPath: "Supermarkets > Food Cupboard",
  },
  {
    id: 73,
    parentCategory: 12,
    name: "Juices",
    completeName: "Supermarkets > Food Cupboard > Juices",
    parentPath: "Supermarkets > Food Cupboard",
  },
  {
    id: 74,
    parentCategory: 12,
    name: "Soft Drinks",
    completeName: "Supermarkets > Food Cupboard > Soft Drinks",
    parentPath: "Supermarkets > Food Cupboard",
  },
  {
    id: 75,
    parentCategory: 12,
    name: "Canned & Packaged Foods",
    completeName: "Supermarkets > Food Cupboard > Canned & Packaged Foods",
    parentPath: "Supermarkets > Food Cupboard",
  },
  {
    id: 76,
    parentCategory: 12,
    name: "Candy & Chocolate",
    completeName: "Supermarkets > Food Cupboard > Candy & Chocolate",
    parentPath: "Supermarkets > Food Cupboard",
  },
  {
    id: 77,
    parentCategory: 12,
    name: "Syrups, Sugars & Sweeteners",
    completeName: "Supermarkets > Food Cupboard > Syrups, Sugars & Sweeteners",
    parentPath: "Supermarkets > Food Cupboard",
  },
  {
    id: 78,
    parentCategory: 13,
    name: "Soft Drink",
    completeName: "Supermarkets > Beverages > Soft Drink",
    parentPath: "Supermarkets > Beverages",
  },
  {
    id: 79,
    parentCategory: 13,
    name: "Milk & Cream",
    completeName: "Supermarkets > Beverages > Milk & Cream",
    parentPath: "Supermarkets > Beverages",
  },
  {
    id: 80,
    parentCategory: 13,
    name: "Energy Drink",
    completeName: "Supermarkets > Beverages > Energy Drink",
    parentPath: "Supermarkets > Beverages",
  },
  {
    id: 81,
    parentCategory: 13,
    name: "Bottled Beverages",
    completeName: "Supermarkets > Beverages > Bottled Beverages",
    parentPath: "Supermarkets > Beverages",
  },
  {
    id: 82,
    parentCategory: 14,
    name: "Laundry",
    completeName: "Supermarkets > Household Cleaning > Laundry",
    parentPath: "Supermarkets > Household Cleaning",
  },
  {
    id: 83,
    parentCategory: 14,
    name: "Air Fresheners",
    completeName: "Supermarkets > Household Cleaning > Air Fresheners",
    parentPath: "Supermarkets > Household Cleaning",
  },
  {
    id: 84,
    parentCategory: 14,
    name: "Toilet Paper & Wipes",
    completeName: "Supermarkets > Household Cleaning > Toilet Paper & Wipes",
    parentPath: "Supermarkets > Household Cleaning",
  },
  {
    id: 85,
    parentCategory: 14,
    name: "Bathroom Cleaners",
    completeName: "Supermarkets > Household Cleaning > Bathroom Cleaners",
    parentPath: "Supermarkets > Household Cleaning",
  },
  {
    id: 86,
    parentCategory: 14,
    name: "Dishwashing",
    completeName: "Supermarkets > Household Cleaning > Dishwashing",
    parentPath: "Supermarkets > Household Cleaning",
  },
  {
    id: 87,
    parentCategory: 14,
    name: "Cleaning Tools",
    completeName: "Supermarkets > Household Cleaning > Cleaning Tools",
    parentPath: "Supermarkets > Household Cleaning",
  },
  {
    id: 88,
    parentCategory: 15,
    name: "Beers",
    completeName: "Supermarkets > Beer, Wine & Spirits > Beers",
    parentPath: "Supermarkets > Beer, Wine & Spirits",
  },
  {
    id: 89,
    parentCategory: 15,
    name: "Vodka",
    completeName: "Supermarkets > Beer, Wine & Spirits > Vodka",
    parentPath: "Supermarkets > Beer, Wine & Spirits",
  },
  {
    id: 90,
    parentCategory: 15,
    name: "Red Wine",
    completeName: "Supermarkets > Beer, Wine & Spirits > Red Wine",
    parentPath: "Supermarkets > Beer, Wine & Spirits",
  },
  {
    id: 91,
    parentCategory: 15,
    name: "Champagne & Sparkling Wine",
    completeName:
      "Supermarkets > Beer, Wine & Spirits > Champagne & Sparkling Wine",
    parentPath: "Supermarkets > Beer, Wine & Spirits",
  },
  {
    id: 92,
    parentCategory: 15,
    name: "White Wine",
    completeName: "Supermarkets > Beer, Wine & Spirits > White Wine",
    parentPath: "Supermarkets > Beer, Wine & Spirits",
  },
  {
    id: 93,
    parentCategory: 15,
    name: "Whiskey",
    completeName: "Supermarkets > Beer, Wine & Spirits > Whiskey",
    parentPath: "Supermarkets > Beer, Wine & Spirits",
  },
  {
    id: 94,
    parentCategory: 15,
    name: "Liquors",
    completeName: "Supermarkets > Beer, Wine & Spirits > Liquors",
    parentPath: "Supermarkets > Beer, Wine & Spirits",
  },
  {
    id: 95,
    parentCategory: 16,
    name: "Disposable Diapers",
    completeName: "Supermarkets > Baby Products > Disposable Diapers",
    parentPath: "Supermarkets > Baby Products",
  },
  {
    id: 96,
    parentCategory: 16,
    name: "Bottle Feeding",
    completeName: "Supermarkets > Baby Products > Bottle Feeding",
    parentPath: "Supermarkets > Baby Products",
  },
  {
    id: 97,
    parentCategory: 16,
    name: "Wipes & Refills",
    completeName: "Supermarkets > Baby Products > Wipes & Refills",
    parentPath: "Supermarkets > Baby Products",
  },
  {
    id: 98,
    parentCategory: 17,
    name: "Concealers & Color Correctors",
    completeName: "Health & Beauty > Make Up > Concealers & Color Correctors",
    parentPath: "Health & Beauty > Make Up",
  },
  {
    id: 99,
    parentCategory: 17,
    name: "Foundation",
    completeName: "Health & Beauty > Make Up > Foundation",
    parentPath: "Health & Beauty > Make Up",
  },
  {
    id: 100,
    parentCategory: 17,
    name: "Powder",
    completeName: "Health & Beauty > Make Up > Powder",
    parentPath: "Health & Beauty > Make Up",
  },
  {
    id: 101,
    parentCategory: 17,
    name: "Lipstick",
    completeName: "Health & Beauty > Make Up > Lipstick",
    parentPath: "Health & Beauty > Make Up",
  },
  {
    id: 102,
    parentCategory: 17,
    name: "Eyeliner & Kajal",
    completeName: "Health & Beauty > Make Up > Eyeliner & Kajal",
    parentPath: "Health & Beauty > Make Up",
  },
  {
    id: 103,
    parentCategory: 17,
    name: "Mascara",
    completeName: "Health & Beauty > Make Up > Mascara",
    parentPath: "Health & Beauty > Make Up",
  },
  {
    id: 104,
    parentCategory: 18,
    name: "Skin Care",
    completeName: "Health & Beauty > Personal Care > Skin Care",
    parentPath: "Health & Beauty > Personal Care",
  },
  {
    id: 105,
    parentCategory: 2,
    name: "Bath & Bathing Accessories",
    completeName:
      "Health & Beauty > Personal Care > Bath & Bathing Accessories",
    parentPath: "Health & Beauty > Personal Care",
  },
  {
    id: 106,
    parentCategory: 2,
    name: "Sunscreens & Tanning Products",
    completeName:
      "Health & Beauty > Personal Care > Sunscreens & Tanning Products",
    parentPath: "Health & Beauty > Personal Care",
  },
  {
    id: 107,
    parentCategory: 2,
    name: "Contraceptives & Lubricants",
    completeName:
      "Health & Beauty > Personal Care > Contraceptives & Lubricants",
    parentPath: "Health & Beauty > Personal Care",
  },
  {
    id: 108,
    parentCategory: 2,
    name: "Piercing & Tattoo Supplies",
    completeName:
      "Health & Beauty > Personal Care > Piercing & Tattoo Supplies",
    parentPath: "Health & Beauty > Personal Care",
  },
  {
    id: 109,
    parentCategory: 2,
    name: "Deodorants & Antiperspirants",
    completeName:
      "Health & Beauty > Personal Care > Deodorants & Antiperspirants",
    parentPath: "Health & Beauty > Personal Care",
  },
  {
    id: 110,
    parentCategory: 18,
    name: "Lip Care",
    completeName: "Health & Beauty > Personal Care > Lip Care",
    parentPath: "Health & Beauty > Personal Care",
  },
  {
    id: 111,
    parentCategory: 19,
    name: "Women's",
    completeName: "Health & Beauty > Fragrances > Women's",
    parentPath: "Health & Beauty > Fragrances",
  },
  {
    id: 112,
    parentCategory: 19,
    name: "Men's",
    completeName: "Health & Beauty > Fragrances > Men's",
    parentPath: "Health & Beauty > Fragrances",
  },
  {
    id: 113,
    parentCategory: 20,
    name: "Hair Accessories",
    completeName: "Health & Beauty > Hair Care > Hair Accessories",
    parentPath: "Health & Beauty > Hair Care",
  },
  {
    id: 114,
    parentCategory: 20,
    name: "Hair Cutting Tools",
    completeName: "Health & Beauty > Hair Care > Hair Cutting Tools",
    parentPath: "Health & Beauty > Hair Care",
  },
  {
    id: 115,
    parentCategory: 20,
    name: "Shampoo & Conditioner",
    completeName: "Health & Beauty > Hair Care > Shampoo & Conditioner",
    parentPath: "Health & Beauty > Hair Care",
  },
  {
    id: 116,
    parentCategory: 20,
    name: "Wigs & Accessories",
    completeName: "Health & Beauty > Hair Care > Wigs & Accessories",
    parentPath: "Health & Beauty > Hair Care",
  },
  {
    id: 117,
    parentCategory: 21,
    name: "Teeth Whitening",
    completeName: "Health & Beauty > Oral Care > Teeth Whitening",
    parentPath: "Health & Beauty > Oral Care",
  },
  {
    id: 118,
    parentCategory: 21,
    name: "Toothbrushes",
    completeName: "Health & Beauty > Oral Care > Toothbrushes",
    parentPath: "Health & Beauty > Oral Care",
  },
  {
    id: 119,
    parentCategory: 21,
    name: "Toothpaste",
    completeName: "Health & Beauty > Oral Care > Toothpaste",
    parentPath: "Health & Beauty > Oral Care",
  },
  {
    id: 120,
    parentCategory: 22,
    name: "First Aid",
    completeName: "Health & Beauty > Health Care > First Aid",
    parentPath: "Health & Beauty > Health Care",
  },
  {
    id: 121,
    parentCategory: 2,
    name: "Medical Supplies & Equipment",
    completeName:
      "Health & Beauty > Health Care > Medical Supplies & Equipment",
    parentPath: "Health & Beauty > Health Care",
  },
  {
    id: 122,
    parentCategory: 22,
    name: "Alternative Medicine",
    completeName: "Health & Beauty > Health Care > Alternative Medicine",
    parentPath: "Health & Beauty > Health Care",
  },
  {
    id: 123,
    parentCategory: 22,
    name: "Feminine Care",
    completeName: "Health & Beauty > Health Care > Feminine Care",
    parentPath: "Health & Beauty > Health Care",
  },
  {
    id: 124,
    parentCategory: 22,
    name: "Diabetes Care",
    completeName: "Health & Beauty > Health Care > Diabetes Care",
    parentPath: "Health & Beauty > Health Care",
  },
  {
    id: 125,
    parentCategory: 23,
    name: "Herbal Supplements",
    completeName:
      "Health & Beauty > Vitamins & Dietary Supplements > Herbal Supplements",
    parentPath: "Health & Beauty > Vitamins & Dietary Supplements",
  },
  {
    id: 126,
    parentCategory: 23,
    name: "Vitamins & Minerals",
    completeName:
      "Health & Beauty > Vitamins & Dietary Supplements > Vitamins & Minerals",
    parentPath: "Health & Beauty > Vitamins & Dietary Supplements",
  },
  {
    id: 127,
    parentCategory: 23,
    name: "Supplements",
    completeName:
      "Health & Beauty > Vitamins & Dietary Supplements > Supplements",
    parentPath: "Health & Beauty > Vitamins & Dietary Supplements",
  },
  {
    id: 128,
    parentCategory: 23,
    name: "Multi & Prenatal Vitamins",
    completeName:
      "Health & Beauty > Vitamins & Dietary Supplements > Multi & Prenatal Vitamins",
    parentPath: "Health & Beauty > Vitamins & Dietary Supplements",
  },
  {
    id: 129,
    parentCategory: 24,
    name: "Bath",
    completeName: "Home & Office > Home & Kitchen > Bath",
    parentPath: "Home & Office > Home & Kitchen",
  },
  {
    id: 130,
    parentCategory: 24,
    name: "Bedding",
    completeName: "Home & Office > Home & Kitchen > Bedding",
    parentPath: "Home & Office > Home & Kitchen",
  },
  {
    id: 131,
    parentCategory: 24,
    name: "Home Decor",
    completeName: "Home & Office > Home & Kitchen > Home Decor",
    parentPath: "Home & Office > Home & Kitchen",
  },
  {
    id: 132,
    parentCategory: 24,
    name: "Home Furniture",
    completeName: "Home & Office > Home & Kitchen > Home Furniture",
    parentPath: "Home & Office > Home & Kitchen",
  },
  {
    id: 133,
    parentCategory: 24,
    name: "Vacuums & Floor Care",
    completeName: "Home & Office > Home & Kitchen > Vacuums & Floor Care",
    parentPath: "Home & Office > Home & Kitchen",
  },
  {
    id: 134,
    parentCategory: 24,
    name: "Wall Art",
    completeName: "Home & Office > Home & Kitchen > Wall Art",
    parentPath: "Home & Office > Home & Kitchen",
  },
  {
    id: 135,
    parentCategory: 24,
    name: "Cookware",
    completeName: "Home & Office > Home & Kitchen > Cookware",
    parentPath: "Home & Office > Home & Kitchen",
  },
  {
    id: 136,
    parentCategory: 24,
    name: "Bakeware",
    completeName: "Home & Office > Home & Kitchen > Bakeware",
    parentPath: "Home & Office > Home & Kitchen",
  },
  {
    id: 137,
    parentCategory: 24,
    name: "Small Appliances",
    completeName: "Home & Office > Home & Kitchen > Small Appliances",
    parentPath: "Home & Office > Home & Kitchen",
  },
  {
    id: 138,
    parentCategory: 3,
    name: "Cutlery & Knife Accessories",
    completeName:
      "Home & Office > Home & Kitchen > Cutlery & Knife Accessories",
    parentPath: "Home & Office > Home & Kitchen",
  },
  {
    id: 139,
    parentCategory: 24,
    name: "Household Chemicals",
    completeName: "Home & Office > Home & Kitchen > Household Chemicals",
    parentPath: "Home & Office > Home & Kitchen",
  },
  {
    id: 140,
    parentCategory: 25,
    name: "Office & School Supplies",
    completeName: "Home & Office > Office Products > Office & School Supplies",
    parentPath: "Home & Office > Office Products",
  },
  {
    id: 141,
    parentCategory: 3,
    name: "Office Furniture & Lighting",
    completeName:
      "Home & Office > Office Products > Office Furniture & Lighting",
    parentPath: "Home & Office > Office Products",
  },
  {
    id: 142,
    parentCategory: 25,
    name: "Packaging Materials",
    completeName: "Home & Office > Office Products > Packaging Materials",
    parentPath: "Home & Office > Office Products",
  },
  {
    id: 143,
    parentCategory: 26,
    name: "Kitchen & Dining",
    completeName: "Home & Office > Home & Office Furniture > Kitchen & Dining",
    parentPath: "Home & Office > Home & Office Furniture",
  },
  {
    id: 144,
    parentCategory: 26,
    name: "Lighting",
    completeName: "Home & Office > Home & Office Furniture > Lighting",
    parentPath: "Home & Office > Home & Office Furniture",
  },
  {
    id: 145,
    parentCategory: 26,
    name: "Stationery",
    completeName: "Home & Office > Home & Office Furniture > Stationery",
    parentPath: "Home & Office > Home & Office Furniture",
  },
  {
    id: 146,
    parentCategory: 26,
    name: "Storage & Organization",
    completeName:
      "Home & Office > Home & Office Furniture > Storage & Organization",
    parentPath: "Home & Office > Home & Office Furniture",
  },
  {
    id: 147,
    parentCategory: 27,
    name: "Blenders",
    completeName: "Appliances > Small Appliances > Blenders",
    parentPath: "Appliances > Small Appliances",
  },
  {
    id: 148,
    parentCategory: 27,
    name: "Deep Fryers",
    completeName: "Appliances > Small Appliances > Deep Fryers",
    parentPath: "Appliances > Small Appliances",
  },
  {
    id: 149,
    parentCategory: 27,
    name: "Juicers",
    completeName: "Appliances > Small Appliances > Juicers",
    parentPath: "Appliances > Small Appliances",
  },
  {
    id: 150,
    parentCategory: 27,
    name: "Air Fryers",
    completeName: "Appliances > Small Appliances > Air Fryers",
    parentPath: "Appliances > Small Appliances",
  },
  {
    id: 151,
    parentCategory: 27,
    name: "Rice Cookers",
    completeName: "Appliances > Small Appliances > Rice Cookers",
    parentPath: "Appliances > Small Appliances",
  },
  {
    id: 152,
    parentCategory: 27,
    name: "Toasters & Ovens",
    completeName: "Appliances > Small Appliances > Toasters & Ovens",
    parentPath: "Appliances > Small Appliances",
  },
  {
    id: 153,
    parentCategory: 27,
    name: "Microwaves",
    completeName: "Appliances > Small Appliances > Microwaves",
    parentPath: "Appliances > Small Appliances",
  },
  {
    id: 154,
    parentCategory: 27,
    name: "Bundles",
    completeName: "Appliances > Small Appliances > Bundles",
    parentPath: "Appliances > Small Appliances",
  },
  {
    id: 155,
    parentCategory: 27,
    name: "Vacuum Cleaners",
    completeName: "Appliances > Small Appliances > Vacuum Cleaners",
    parentPath: "Appliances > Small Appliances",
  },
  {
    id: 156,
    parentCategory: 27,
    name: "Kettles",
    completeName: "Appliances > Small Appliances > Kettles",
    parentPath: "Appliances > Small Appliances",
  },
  {
    id: 157,
    parentCategory: 27,
    name: "Yam Pounders",
    completeName: "Appliances > Small Appliances > Yam Pounders",
    parentPath: "Appliances > Small Appliances",
  },
  {
    id: 158,
    parentCategory: 27,
    name: "Irons",
    completeName: "Appliances > Small Appliances > Irons",
    parentPath: "Appliances > Small Appliances",
  },
  {
    id: 159,
    parentCategory: 28,
    name: "Washing Machines",
    completeName: "Appliances > Large Appliances > Washing Machines",
    parentPath: "Appliances > Large Appliances",
  },
  {
    id: 160,
    parentCategory: 28,
    name: "Fridges",
    completeName: "Appliances > Large Appliances > Fridges",
    parentPath: "Appliances > Large Appliances",
  },
  {
    id: 161,
    parentCategory: 28,
    name: "Freezers",
    completeName: "Appliances > Large Appliances > Freezers",
    parentPath: "Appliances > Large Appliances",
  },
  {
    id: 162,
    parentCategory: 28,
    name: "Air Conditioners",
    completeName: "Appliances > Large Appliances > Air Conditioners",
    parentPath: "Appliances > Large Appliances",
  },
  {
    id: 163,
    parentCategory: 28,
    name: "Heaters",
    completeName: "Appliances > Large Appliances > Heaters",
    parentPath: "Appliances > Large Appliances",
  },
  {
    id: 164,
    parentCategory: 28,
    name: "Fans",
    completeName: "Appliances > Large Appliances > Fans",
    parentPath: "Appliances > Large Appliances",
  },
  {
    id: 165,
    parentCategory: 28,
    name: "Air Purifiers",
    completeName: "Appliances > Large Appliances > Air Purifiers",
    parentPath: "Appliances > Large Appliances",
  },
  {
    id: 166,
    parentCategory: 28,
    name: "Water Dispensers",
    completeName: "Appliances > Large Appliances > Water Dispensers",
    parentPath: "Appliances > Large Appliances",
  },
  {
    id: 167,
    parentCategory: 28,
    name: "Generators & Inverters",
    completeName: "Appliances > Large Appliances > Generators & Inverters",
    parentPath: "Appliances > Large Appliances",
  },
  {
    id: 168,
    parentCategory: 30,
    name: "Smartphones",
    completeName: "Phones & Tablets > Mobile Phones > Smartphones",
    parentPath: "Phones & Tablets > Mobile Phones",
  },
  {
    id: 169,
    parentCategory: 30,
    name: "Basic Phones",
    completeName: "Phones & Tablets > Mobile Phones > Basic Phones",
    parentPath: "Phones & Tablets > Mobile Phones",
  },
  {
    id: 170,
    parentCategory: 30,
    name: "Refurbished Phones",
    completeName: "Phones & Tablets > Mobile Phones > Refurbished Phones",
    parentPath: "Phones & Tablets > Mobile Phones",
  },
  {
    id: 171,
    parentCategory: 30,
    name: "Smart Watches & Trackers",
    completeName: "Phones & Tablets > Mobile Phones > Smart Watches & Trackers",
    parentPath: "Phones & Tablets > Mobile Phones",
  },
  {
    id: 172,
    parentCategory: 31,
    name: "iPads",
    completeName: "Phones & Tablets > Tablets > iPads",
    parentPath: "Phones & Tablets > Tablets",
  },
  {
    id: 173,
    parentCategory: 31,
    name: "Android Tablets",
    completeName: "Phones & Tablets > Tablets > Android Tablets",
    parentPath: "Phones & Tablets > Tablets",
  },
  {
    id: 174,
    parentCategory: 31,
    name: "Android Tablets",
    completeName: "Phones & Tablets > Tablets > Android Tablets",
    parentPath: "Phones & Tablets > Tablets",
  },
  {
    id: 175,
    parentCategory: 31,
    name: "Tablet Accessories",
    completeName: "Phones & Tablets > Tablets > Tablet Accessories",
    parentPath: "Phones & Tablets > Tablets",
  },
  {
    id: 176,
    parentCategory: 32,
    name: "Accessory Kits",
    completeName: "Phones & Tablets > Mobile Accessories > Accessory Kits",
    parentPath: "Phones & Tablets > Mobile Accessories",
  },
  {
    id: 177,
    parentCategory: 32,
    name: "Adapters",
    completeName: "Phones & Tablets > Mobile Accessories > Adapters",
    parentPath: "Phones & Tablets > Mobile Accessories",
  },
  {
    id: 178,
    parentCategory: 32,
    name: "Batteries",
    completeName: "Phones & Tablets > Mobile Accessories > Batteries",
    parentPath: "Phones & Tablets > Mobile Accessories",
  },
  {
    id: 179,
    parentCategory: 32,
    name: "Battery Chargers",
    completeName: "Phones & Tablets > Mobile Accessories > Battery Chargers",
    parentPath: "Phones & Tablets > Mobile Accessories",
  },
  {
    id: 180,
    parentCategory: 32,
    name: "Bluetooth Headsets",
    completeName: "Phones & Tablets > Mobile Accessories > Bluetooth Headsets",
    parentPath: "Phones & Tablets > Mobile Accessories",
  },
  {
    id: 181,
    parentCategory: 32,
    name: "Cables",
    completeName: "Phones & Tablets > Mobile Accessories > Cables",
    parentPath: "Phones & Tablets > Mobile Accessories",
  },
  {
    id: 182,
    parentCategory: 32,
    name: "Car Accessories",
    completeName: "Phones & Tablets > Mobile Accessories > Car Accessories",
    parentPath: "Phones & Tablets > Mobile Accessories",
  },
  {
    id: 183,
    parentCategory: 32,
    name: "Chargers",
    completeName: "Phones & Tablets > Mobile Accessories > Chargers",
    parentPath: "Phones & Tablets > Mobile Accessories",
  },
  {
    id: 184,
    parentCategory: 5,
    name: "Earphones & Headsets",
    completeName:
      "Phones & Tablets > Mobile Accessories > Earphones & Headsets",
    parentPath: "Phones & Tablets > Mobile Accessories",
  },
  {
    id: 185,
    parentCategory: 32,
    name: "MicroSD Cards",
    completeName: "Phones & Tablets > Mobile Accessories > MicroSD Cards",
    parentPath: "Phones & Tablets > Mobile Accessories",
  },
  {
    id: 186,
    parentCategory: 32,
    name: "Screen Protectors",
    completeName: "Phones & Tablets > Mobile Accessories > Screen Protectors",
    parentPath: "Phones & Tablets > Mobile Accessories",
  },
  {
    id: 187,
    parentCategory: 32,
    name: "Selfie Sticks & Tripods",
    completeName:
      "Phones & Tablets > Mobile Accessories > Selfie Sticks & Tripods",
    parentPath: "Phones & Tablets > Mobile Accessories",
  },
  {
    id: 188,
    parentCategory: 32,
    name: "Smart Watches",
    completeName: "Phones & Tablets > Mobile Accessories > Smart Watches",
    parentPath: "Phones & Tablets > Mobile Accessories",
  },
  {
    id: 189,
    parentCategory: 33,
    name: "iPhone 15 Pro Max",
    completeName: "Phones & Tablets > Top Smart Phones > iPhone 15 Pro Max",
    parentPath: "Phones & Tablets > Top Smart Phones",
  },
  {
    id: 190,
    parentCategory: 33,
    name: "Samsung Galaxy S22 Ultra",
    completeName:
      "Phones & Tablets > Top Smart Phones > Samsung Galaxy S22 Ultra",
    parentPath: "Phones & Tablets > Top Smart Phones",
  },
  {
    id: 191,
    parentCategory: 33,
    name: "iPhone 14",
    completeName: "Phones & Tablets > Top Smart Phones > iPhone 14",
    parentPath: "Phones & Tablets > Top Smart Phones",
  },
  {
    id: 192,
    parentCategory: 33,
    name: "Nokia 7.2",
    completeName: "Phones & Tablets > Top Smart Phones > Nokia 7.2",
    parentPath: "Phones & Tablets > Top Smart Phones",
  },
  {
    id: 193,
    parentCategory: 33,
    name: "Google Pixel",
    completeName: "Phones & Tablets > Top Smart Phones > Google Pixel",
    parentPath: "Phones & Tablets > Top Smart Phones",
  },
  {
    id: 194,
    parentCategory: 34,
    name: "Samsung",
    completeName: "Phones & Tablets > Top Phone Brands > Samsung",
    parentPath: "Phones & Tablets > Top Phone Brands",
  },
  {
    id: 195,
    parentCategory: 34,
    name: "Apple",
    completeName: "Phones & Tablets > Top Phone Brands > Apple",
    parentPath: "Phones & Tablets > Top Phone Brands",
  },
  {
    id: 195,
    parentCategory: 34,
    name: "Huawei",
    completeName: "Phones & Tablets > Top Phone Brands > Huawei",
    parentPath: "Phones & Tablets > Top Phone Brands",
  },
  {
    id: 196,
    parentCategory: 34,
    name: "Nokia",
    completeName: "Phones & Tablets > Top Phone Brands > Nokia",
    parentPath: "Phones & Tablets > Top Phone Brands",
  },
  {
    id: 197,
    parentCategory: 34,
    name: "Xiaomi",
    completeName: "Phones & Tablets > Top Phone Brands > Xiaomi",
    parentPath: "Phones & Tablets > Top Phone Brands",
  },
  {
    id: 198,
    parentCategory: 34,
    name: "Tecno",
    completeName: "Phones & Tablets > Top Phone Brands > Tecno",
    parentPath: "Phones & Tablets > Top Phone Brands",
  },
  {
    id: 199,
    parentCategory: 35,
    name: "Desktops",
    completeName: "Computing > Computers > Desktops",
    parentPath: "Computing > Computers",
  },
  {
    id: 200,
    parentCategory: 35,
    name: "Laptops",
    completeName: "Computing > Computers > Laptops",
    parentPath: "Computing > Computers",
  },
  {
    id: 201,
    parentCategory: 36,
    name: "External Hard Drives",
    completeName: "Computing > Data Storage > External Hard Drives",
    parentPath: "Computing > Data Storage",
  },
  {
    id: 202,
    parentCategory: 36,
    name: "USB Flash Drives",
    completeName: "Computing > Data Storage > USB Flash Drives",
    parentPath: "Computing > Data Storage",
  },
  {
    id: 203,
    parentCategory: 36,
    name: "External Solid State",
    completeName: "Computing > Data Storage > External Solid State",
    parentPath: "Computing > Data Storage",
  },
  {
    id: 201,
    parentCategory: 37,
    name: "Inkjet Printers",
    completeName: "Computing > Printers > Inkjet Printers",
    parentPath: "Computing > Printers",
  },
  {
    id: 202,
    parentCategory: 37,
    name: "Laser Printers",
    completeName: "Computing > Printers > Laser Printers",
    parentPath: "Computing > Printers",
  },
  {
    id: 203,
    parentCategory: 37,
    name: "Printer Ink & Toner",
    completeName: "Computing > Printers > Printer Ink & Toner",
    parentPath: "Computing > Printers",
  },
  {
    id: 204,
    parentCategory: 38,
    name: "Keyboards & Mice",
    completeName: "Computing > Computer Accessories > Keyboards & Mice",
    parentPath: "Computing > Computer Accessories",
  },
  {
    id: 205,
    parentCategory: 38,
    name: "Uninterrupted Power Supply",
    completeName: "Computing > Computer Accessories > Printe",
    parentPath: "Computing > Computer Accessories",
  },
  {
    id: 206,
    parentCategory: 38,
    name: "Memory Cards",
    completeName: "Computing > Computer Accessories > Memory Cards",
    parentPath: "Computing > Computer Accessories",
  },
  {
    id: 207,
    parentCategory: 38,
    name: "Batteries",
    completeName: "Computing > Computer Accessories > Batteries",
    parentPath: "Computing > Computer Accessories",
  },
  {
    id: 208,
    parentCategory: 38,
    name: "Scanners",
    completeName: "Computing > Computer Accessories > Scanners",
    parentPath: "Computing > Computer Accessories",
  },
  {
    id: 209,
    parentCategory: 38,
    name: "Video Projectors",
    completeName: "Computing > Computer Accessories > Video Projectors",
    parentPath: "Computing > Computer Accessories",
  },
  {
    id: 210,
    parentCategory: 39,
    name: "HP",
    completeName: "Computing > Top Brands > HP",
    parentPath: "Computing > Top Brands",
  },
  {
    id: 211,
    parentCategory: 39,
    name: "Lenovo",
    completeName: "Computing > Top Brands > Lenovo",
    parentPath: "Computing > Top Brands",
  },
  {
    id: 212,
    parentCategory: 39,
    name: "Apple",
    completeName: "Computing > Top Brands > Apple",
    parentPath: "Computing > Top Brands",
  },
  {
    id: 213,
    parentCategory: 39,
    name: "ASUS",
    completeName: "Computing > Top Brands > ASUS",
    parentPath: "Computing > Top Brands",
  },
  {
    id: 214,
    parentCategory: 39,
    name: "Huawei",
    completeName: "Computing > Top Brands > Huawei",
    parentPath: "Computing > Top Brands",
  },
  {
    id: 215,
    parentCategory: 39,
    name: "Microsoft",
    completeName: "Computing > Top Brands > Microsoft",
    parentPath: "Computing > Top Brands",
  },
  {
    id: 216,
    parentCategory: 39,
    name: "Kingston",
    completeName: "Computing > Top Brands > Kingston",
    parentPath: "Computing > Top Brands",
  },
  {
    id: 217,
    parentCategory: 39,
    name: "Seagate",
    completeName: "Computing > Top Brands > Seagate",
    parentPath: "Computing > Top Brands",
  },
  {
    id: 218,
    parentCategory: 39,
    name: "Samsung",
    completeName: "Computing > Top Brands > Samsung",
    parentPath: "Computing > Top Brands",
  },
  {
    id: 219,
    parentCategory: 39,
    name: "Sandisk",
    completeName: "Computing > Top Brands > Sandisk",
    parentPath: "Computing > Top Brands",
  },
  {
    id: 220,
    parentCategory: 39,
    name: "Toshiba",
    completeName: "Computing > Top Brands > Toshiba",
    parentPath: "Computing > Top Brands",
  },
  {
    id: 221,
    parentCategory: 40,
    name: "Clothing",
    completeName: "Fashion > Women's Fashion > Clothing",
    parentPath: "Fashion > Women's Fashion",
  },
  {
    id: 222,
    parentCategory: 40,
    name: "Shoes",
    completeName: "Fashion > Women's Fashion > Shoes",
    parentPath: "Fashion > Women's Fashion",
  },
  {
    id: 223,
    parentCategory: 40,
    name: "Accessories",
    completeName: "Fashion > Women's Fashion > Accessories",
    parentPath: "Fashion > Women's Fashion",
  },
  {
    id: 224,
    parentCategory: 40,
    name: "Jewelry",
    completeName: "Fashion > Women's Fashion > Jewelry",
    parentPath: "Fashion > Women's Fashion",
  },
  {
    id: 225,
    parentCategory: 40,
    name: "Handbags & Wallets",
    completeName: "Fashion > Women's Fashion > Handbags & Wallets",
    parentPath: "Fashion > Women's Fashion",
  },
  {
    id: 226,
    parentCategory: 40,
    name: "Underwear & Sleepwear",
    completeName: "Fashion > Women's Fashion > Underwear & Sleepwear",
    parentPath: "Fashion > Women's Fashion",
  },
  {
    id: 227,
    parentCategory: 40,
    name: "Maternity",
    completeName: "Fashion > Women's Fashion > Maternity",
    parentPath: "Fashion > Women's Fashion",
  },
  {
    id: 228,
    parentCategory: 40,
    name: "Dresses",
    completeName: "Fashion > Women's Fashion > Dresses",
    parentPath: "Fashion > Women's Fashion",
  },
  {
    id: 229,
    parentCategory: 40,
    name: "Traditional",
    completeName: "Fashion > Women's Fashion > Traditional",
    parentPath: "Fashion > Women's Fashion",
  },
  {
    id: 230,
    parentCategory: 40,
    name: "Beach & Swimwear",
    completeName: "Fashion > Women's Fashion > Beach & Swimwear",
    parentPath: "Fashion > Women's Fashion",
  },
  {
    id: 231,
    parentCategory: 40,
    name: "Flats",
    completeName: "Fashion > Women's Fashion > Flats",
    parentPath: "Fashion > Women's Fashion",
  },
  {
    id: 232,
    parentCategory: 41,
    name: "Boy's Fashion",
    completeName: "Fashion > Kid's Fashion > Boy's Fashion",
    parentPath: "Fashion > Kid's Fashion",
  },
  {
    id: 233,
    parentCategory: 41,
    name: "Girl's Fashion",
    completeName: "Fashion > Kid's Fashion > Girl's Fashion",
    parentPath: "Fashion > Kid's Fashion",
  },
  {
    id: 234,
    parentCategory: 42,
    name: "Clothing",
    completeName: "Fashion > Men's Fashion > Clothing",
    parentPath: "Fashion > Men's Fashion",
  },
  {
    id: 235,
    parentCategory: 42,
    name: "Shoes",
    completeName: "Fashion > Men's Fashion > Shoes",
    parentPath: "Fashion > Men's Fashion",
  },
  {
    id: 235,
    parentCategory: 42,
    name: "Accessories",
    completeName: "Fashion > Men's Fashion > Accessories",
    parentPath: "Fashion > Men's Fashion",
  },
  {
    id: 236,
    parentCategory: 42,
    name: "Underwear & Sleepwear",
    completeName: "Fashion > Men's Fashion > Underwear & Sleepwear",
    parentPath: "Fashion > Men's Fashion",
  },
  {
    id: 237,
    parentCategory: 42,
    name: "Traditional & Cultural Wear",
    completeName: "Fashion > Men's Fashion > Traditional & Cultural Wear",
    parentPath: "Fashion > Men's Fashion",
  },
  {
    id: 238,
    parentCategory: 42,
    name: "T-Shirts",
    completeName: "Fashion > Men's Fashion > T-Shirts",
    parentPath: "Fashion > Men's Fashion",
  },
  {
    id: 239,
    parentCategory: 42,
    name: "Polo Shirts",
    completeName: "Fashion > Men's Fashion > Polo Shirts",
    parentPath: "Fashion > Men's Fashion",
  },
  {
    id: 240,
    parentCategory: 42,
    name: "Trousers & Chinos",
    completeName: "Fashion > Men's Fashion > Trousers & Chinos",
    parentPath: "Fashion > Men's Fashion",
  },
  {
    id: 241,
    parentCategory: 42,
    name: "Sneakers",
    completeName: "Fashion > Men's Fashion > Sneakers",
    parentPath: "Fashion > Men's Fashion",
  },
  {
    id: 242,
    parentCategory: 42,
    name: "Jewelry",
    completeName: "Fashion > Men's Fashion > Jewelry",
    parentPath: "Fashion > Men's Fashion",
  },
  {
    id: 243,
    parentCategory: 42,
    name: "Jerseys",
    completeName: "Fashion > Men's Fashion > Jerseys",
    parentPath: "Fashion > Men's Fashion",
  },
  {
    id: 244,
    parentCategory: 43,
    name: "Men's Watches",
    completeName: "Fashion > Watches > Men's Watches",
    parentPath: "Fashion > Watches",
  },
  {
    id: 245,
    parentCategory: 43,
    name: "Women's Watches",
    completeName: "Fashion > Watches > Women's Watches",
    parentPath: "Fashion > Watches",
  },
  {
    id: 246,
    parentCategory: 44,
    name: "Men's Sunglasses",
    completeName: "Fashion > Sunglasses > Men's Sunglasses",
    parentPath: "Fashion > Sunglasses",
  },
  {
    id: 247,
    parentCategory: 44,
    name: "Women's Sunglasses",
    completeName: "Fashion > Sunglasses > Women's Sunglasses",
    parentPath: "Fashion > Sunglasses",
  },
  {
    id: 248,
    parentCategory: 45,
    name: "Adidas",
    completeName: "Fashion > Top Brands > Adidas",
    parentPath: "Fashion > Top Brands",
  },
  {
    id: 249,
    parentCategory: 45,
    name: "DeFacto",
    completeName: "Fashion > Top Brands > DeFacto",
    parentPath: "Fashion > Top Brands",
  },
  {
    id: 250,
    parentCategory: 45,
    name: "Nike",
    completeName: "Fashion > Top Brands > Nike",
    parentPath: "Fashion > Top Brands",
  },
  {
    id: 251,
    parentCategory: 46,
    name: "Baby Boys",
    completeName: "Baby Products > Apparel & Accessories > Baby Boys",
    parentPath: "Baby Products > Apparel & Accessories",
  },
  {
    id: 252,
    parentCategory: 46,
    name: "Baby Girls",
    completeName: "Baby Products > Apparel & Accessories > Baby Girls",
    parentPath: "Baby Products > Apparel & Accessories",
  },
  {
    id: 253,
    parentCategory: 47,
    name: "Disposable Diapers",
    completeName: "Baby Products > Diapering > Disposable Diapers",
    parentPath: "Baby Products > Diapering",
  },
  {
    id: 254,
    parentCategory: 47,
    name: "Diaper Bags",
    completeName: "Baby Products > Diapering > Diaper Bags",
    parentPath: "Baby Products > Diapering",
  },
  {
    id: 256,
    parentCategory: 47,
    name: "Wipes & Holders",
    completeName: "Baby Products > Diapering > Wipes & Holders",
    parentPath: "Baby Products > Diapering",
  },
  {
    id: 257,
    parentCategory: 48,
    name: "Baby & Toddler Toys",
    completeName: "Baby Products > Baby & Toddler Toys > Baby & Toddler Toys",
    parentPath: "Baby Products > Baby & Toddler Toys",
  },
  {
    id: 258,
    parentCategory: 48,
    name: "Music & Sound",
    completeName: "Baby Products > Baby & Toddler Toys > Music & Sound",
    parentPath: "Baby Products > Baby & Toddler Toys",
  },
  {
    id: 259,
    parentCategory: 48,
    name: "Bath Toys",
    completeName: "Baby Products > Baby & Toddler Toys > Bath Toys",
    parentPath: "Baby Products > Baby & Toddler Toys",
  },
  {
    id: 260,
    parentCategory: 49,
    name: "Washcloths & Towels",
    completeName: "Baby Products > Bathing & Skin Care > Washcloths & Towels",
    parentPath: "Baby Products > Bathing & Skin Care",
  },
  {
    id: 261,
    parentCategory: 49,
    name: "Grooming & Healthcare Kits",
    completeName:
      "Baby Products > Bathing & Skin Care > Grooming & Healthcare Kits",
    parentPath: "Baby Products > Bathing & Skin Care",
  },
  {
    id: 262,
    parentCategory: 49,
    name: "Skin Care",
    completeName: "Baby Products > Bathing & Skin Care > Skin Care",
    parentPath: "Baby Products > Bathing & Skin Care",
  },
  {
    id: 263,
    parentCategory: 49,
    name: "Bathing Tubs & Seats",
    completeName: "Baby Products > Bathing & Skin Care > Bathing Tubs & Seats",
    parentPath: "Baby Products > Bathing & Skin Care",
  },
  {
    id: 264,
    parentCategory: 49,
    name: "Bathroom Safety",
    completeName: "Baby Products > Bathing & Skin Care > Bathroom Safety",
    parentPath: "Baby Products > Bathing & Skin Care",
  },
  {
    id: 265,
    parentCategory: 50,
    name: "Bibs & Burp Cloths",
    completeName: "Baby Products > Feeding > Bibs & Burp Cloths",
    parentPath: "Baby Products > Feeding",
  },
  {
    id: 266,
    parentCategory: 50,
    name: "Breastfeeding",
    completeName: "Baby Products > Feeding > Breastfeeding",
    parentPath: "Baby Products > Feeding",
  },
  {
    id: 267,
    parentCategory: 50,
    name: "Bottle-Feeding",
    completeName: "Baby Products > Feeding > Bottle-Feeding",
    parentPath: "Baby Products > Feeding",
  },
  {
    id: 268,
    parentCategory: 50,
    name: "Pacifiers & Accessories",
    completeName: "Baby Products > Feeding > Pacifiers & Accessories",
    parentPath: "Baby Products > Feeding",
  },
  {
    id: 269,
    parentCategory: 51,
    name: "Highchairs & Booster Seats",
    completeName: "Baby Products > Food Storage > Highchairs & Booster Seats",
    parentPath: "Baby Products > Food Storage",
  },
  {
    id: 270,
    parentCategory: 51,
    name: "Solid Feeding",
    completeName: "Baby Products > Food Storage > Solid Feeding",
    parentPath: "Baby Products > Food Storage",
  },
  {
    id: 271,
    parentCategory: 51,
    name: "Backpacks & Carriers",
    completeName: "Baby Products > Gear > Backpacks & Carriers",
    parentPath: "Baby Products > Gear",
  },
  {
    id: 272,
    parentCategory: 51,
    name: "Swings, Jumpers & Bouncers",
    completeName: "Baby Products > Gear > Swings, Jumpers & Bouncers",
    parentPath: "Baby Products > Gear",
  },
  {
    id: 273,
    parentCategory: 52,
    name: "Playstation 5",
    completeName: "Gaming > Playstation > Playstation 5",
    parentPath: "Gaming > Playstation",
  },
  {
    id: 274,
    parentCategory: 52,
    name: "Playstation 4",
    completeName: "Gaming > Playstation > Playstation 4",
    parentPath: "Gaming > Playstation",
  },
  {
    id: 275,
    parentCategory: 52,
    name: "Playstation 3",
    completeName: "Gaming > Playstation > Playstation 3",
    parentPath: "Gaming > Playstation",
  },
  {
    id: 276,
    parentCategory: 52,
    name: "Playstation",
    completeName: "Gaming > Playstation > Playstation",
    parentPath: "Gaming > Playstation",
  },
  {
    id: 277,
    parentCategory: 52,
    name: "Playstation Vita",
    completeName: "Gaming > Playstation > Playstation Vita",
    parentPath: "Gaming > Playstation",
  },
  {
    id: 278,
    parentCategory: 53,
    name: "XBOX",
    completeName: "Gaming > XBox > XBOX",
    parentPath: "Gaming > XBox",
  },
  {
    id: 279,
    parentCategory: 53,
    name: "XBOX One",
    completeName: "Gaming > XBox > XBOX One",
    parentPath: "Gaming > XBox",
  },
  {
    id: 280,
    parentCategory: 53,
    name: "XBOX 360",
    completeName: "Gaming > XBox > XBOX 360",
    parentPath: "Gaming > XBox",
  },
  {
    id: 281,
    parentCategory: 54,
    name: "Nintendo 3DS",
    completeName: "Gaming > Nintendo > Nintendo 3DS",
    parentPath: "Gaming > Nintendo",
  },
  {
    id: 282,
    parentCategory: 54,
    name: "Nintendo DS",
    completeName: "Gaming > Nintendo > Nintendo DS",
    parentPath: "Gaming > Nintendo",
  },
  {
    id: 283,
    parentCategory: 54,
    name: "Nintendo Switch",
    completeName: "Gaming > Nintendo > Nintendo Switch",
    parentPath: "Gaming > Nintendo",
  },
  {
    id: 284,
    parentCategory: 54,
    name: "Nintendo Wii",
    completeName: "Gaming > Nintendo > Nintendo Wii",
    parentPath: "Gaming > Nintendo",
  },
  {
    id: 285,
    parentCategory: 55,
    name: "FIFA '23 PS5",
    completeName: "Gaming > Top Games > FIFA '23 PS5",
    parentPath: "Gaming > Top Games",
  },
  {
    id: 286,
    parentCategory: 55,
    name: "PES '23 PS4",
    completeName: "Gaming > Top Games > PES '23 PS4",
    parentPath: "Gaming > Top Games",
  },
  {
    id: 287,
    parentCategory: 55,
    name: "God of War",
    completeName: "Gaming > Top Games > God of War",
    parentPath: "Gaming > Top Games",
  },
  {
    id: 288,
    parentCategory: 55,
    name: "Spiderman",
    completeName: "Gaming > Top Games > Spiderman",
    parentPath: "Gaming > Top Games",
  },
  {
    id: 289,
    parentCategory: 55,
    name: "Call of Duty",
    completeName: "Gaming > Top Games > Call of Duty",
    parentPath: "Gaming > Top Games",
  },
  {
    id: 290,
    parentCategory: 55,
    name: "Assassin's Creed Valhalla",
    completeName: "Gaming > Top Games > Assassin's Creed Valhalla",
    parentPath: "Gaming > Top Games",
  },
  {
    id: 291,
    parentCategory: 55,
    name: "The Last Of Us",
    completeName: "Gaming > Top Games > The Last Of Us",
    parentPath: "Gaming > Top Games",
  },
  {
    id: 292,
    parentCategory: 55,
    name: "The Witcher 3",
    completeName: "Gaming > Top Games > The Witcher 3",
    parentPath: "Gaming > Top Games",
  },
  {
    id: 293,
    parentCategory: 55,
    name: "Metal Gear Solid",
    completeName: "Gaming > Top Games > Metal Gear Solid",
    parentPath: "Gaming > Top Games",
  },
  {
    id: 294,
    parentCategory: 55,
    name: "Fallout",
    completeName: "Gaming > Top Games > Fallout",
    parentPath: "Gaming > Top Games",
  },
  {
    id: 295,
    parentCategory: 55,
    name: "Madden NFL",
    completeName: "Gaming > Top Games > Madden NFL",
    parentPath: "Gaming > Top Games",
  },
  {
    id: 296,
    parentCategory: 55,
    name: "Far Cry",
    completeName: "Gaming > Top Games > Far Cry",
    parentPath: "Gaming > Top Games",
  },
  {
    id: 297,
    parentCategory: 55,
    name: "Grand Theft Auto",
    completeName: "Gaming > Top Games > Grand Theft Auto",
    parentPath: "Gaming > Top Games",
  },
  {
    id: 298,
    parentCategory: 56,
    name: "Exercise Bikes",
    completeName: "Sports & Outdoor > Cardio Training > Exercise Bikes",
    parentPath: "Sports & Outdoor > Cardio Training",
  },
  {
    id: 299,
    parentCategory: 56,
    name: "Treadmills",
    completeName: "Sports & Outdoor > Cardio Training > Treadmills",
    parentPath: "Sports & Outdoor > Cardio Training",
  },
  {
    id: 300,
    parentCategory: 56,
    name: "Elliptical Trainers",
    completeName: "Sports & Outdoor > Cardio Training > Elliptical Trainers",
    parentPath: "Sports & Outdoor > Cardio Training",
  },
  {
    id: 301,
    parentCategory: 57,
    name: "Strength Training Equipment",
    completeName:
      "Sports & Outdoor > Strength Training Equipment > Strength Training Equipment",
    parentPath: "Sports & Outdoor > Strength Training Equipment",
  },
  {
    id: 302,
    parentCategory: 57,
    name: "Dumbbells",
    completeName: "Sports & Outdoor > Strength Training Equipment > Dumbbells",
    parentPath: "Sports & Outdoor > Strength Training Equipment",
  },
  {
    id: 303,
    parentCategory: 57,
    name: "Bars",
    completeName: "Sports & Outdoor > Strength Training Equipment > Bars",
    parentPath: "Sports & Outdoor > Strength Training Equipment",
  },
  {
    id: 304,
    parentCategory: 58,
    name: "Exercise Bands",
    completeName: "Sports & Outdoor > Accessories > Exercise Bands",
    parentPath: "Sports & Outdoor > Accessories",
  },
  {
    id: 305,
    parentCategory: 58,
    name: "Exercise Mats",
    completeName: "Sports & Outdoor > Accessories > Exercise Mats",
    parentPath: "Sports & Outdoor > Accessories",
  },
  {
    id: 306,
    parentCategory: 58,
    name: "Jump Ropes",
    completeName: "Sports & Outdoor > Accessories > Jump Ropes",
    parentPath: "Sports & Outdoor > Accessories",
  },
  {
    id: 307,
    parentCategory: 58,
    name: "Sports Clothing",
    completeName: "Sports & Outdoor > Accessories > Sports Clothing",
    parentPath: "Sports & Outdoor > Accessories",
  },
  {
    id: 308,
    parentCategory: 59,
    name: "Basketball",
    completeName: "Sports & Outdoor > Team Sports > Basketball",
    parentPath: "Sports & Outdoor > Team Sports",
  },
  {
    id: 309,
    parentCategory: 59,
    name: "Team Sport Accessories",
    completeName: "Sports & Outdoor > Team Sports > Team Sport Accessories",
    parentPath: "Sports & Outdoor > Team Sports",
  },
  {
    id: 310,
    parentCategory: 59,
    name: "Tennis & Racquet Sports",
    completeName: "Sports & Outdoor > Team Sports > Tennis & Racquet Sports",
    parentPath: "Sports & Outdoor > Team Sports",
  },
  {
    id: 311,
    parentCategory: 59,
    name: "Swimming",
    completeName: "Sports & Outdoor > Team Sports > Swimming",
    parentPath: "Sports & Outdoor > Team Sports",
  },
  {
    id: 312,
    parentCategory: 59,
    name: "Cycling",
    completeName: "Sports & Outdoor > Team Sports > Cycling",
    parentPath: "Sports & Outdoor > Team Sports",
  },
  {
    id: 313,
    parentCategory: 60,
    name: "Made in Aba",
    completeName: "Other Categories > Made in Aba > Made in Aba",
    parentPath: "Other Categories > Made in Aba",
  },
  {
    id: 314,
    parentCategory: 60,
    name: "Mami Stores",
    completeName: "Other Categories > Made in Aba > Mami Stores",
    parentPath: "Other Categories > Made in Aba",
  },
  {
    id: 315,
    parentCategory: 60,
    name: "Black Culture",
    completeName: "Other Categories > Made in Aba > Black Culture",
    parentPath: "Other Categories > Made in Aba",
  },
  {
    id: 316,
    parentCategory: 61,
    name: "100% Polyester Fabric",
    completeName: "Other Categories > Raw Materials > 100% Polyester Fabric",
    parentPath: "Other Categories > Raw Materials",
  },
  {
    id: 317,
    parentCategory: 61,
    name: "Cotton Fabric",
    completeName: "Other Categories > Raw Materials > Cotton Fabric",
    parentPath: "Other Categories > Raw Materials",
  },
  {
    id: 318,
    parentCategory: 61,
    name: "Lining Fabric",
    completeName: "Other Categories > Raw Materials > Lining Fabric",
    parentPath: "Other Categories > Raw Materials",
  },
  {
    id: 319,
    parentCategory: 61,
    name: "Synthetic Leather",
    completeName: "Other Categories > Raw Materials > Synthetic Leather",
    parentPath: "Other Categories > Raw Materials",
  },
  {
    id: 320,
    parentCategory: 61,
    name: "Spandex Fabric",
    completeName: "Other Categories > Raw Materials > Spandex Fabric",
    parentPath: "Other Categories > Raw Materials",
  },
  {
    id: 321,
    parentCategory: 61,
    name: "Other Fabric",
    completeName: "Other Categories > Raw Materials > Other Fabric",
    parentPath: "Other Categories > Raw Materials",
  },
  {
    id: 322,
    parentCategory: 61,
    name: "Home Deco Fabric",
    completeName: "Other Categories > Raw Materials > Home Deco Fabric",
    parentPath: "Other Categories > Raw Materials",
  },
  {
    id: 323,
    parentCategory: 61,
    name: "Polyester/Cotton Fabric",
    completeName: "Other Categories > Raw Materials > Polyester/Cotton Fabric",
    parentPath: "Other Categories > Raw Materials",
  },
  {
    id: 324,
    parentCategory: 61,
    name: "Home Deco Fabric",
    completeName: "Other Categories > Raw Materials > Home Deco Fabric",
    parentPath: "Other Categories > Raw Materials",
  },
  {
    id: 325,
    parentCategory: 61,
    name: "Nonwoven Fabric",
    completeName: "Other Categories > Raw Materials > Nonwoven Fabric",
    parentPath: "Other Categories > Raw Materials",
  },
  {
    id: 326,
    parentCategory: 61,
    name: "Embroidery Fabric",
    completeName: "Other Categories > Raw Materials > Embroidery Fabric",
    parentPath: "Other Categories > Raw Materials",
  },
  {
    id: 327,
    parentCategory: 61,
    name: "Feathers",
    completeName: "Other Categories > Raw Materials > Feathers",
    parentPath: "Other Categories > Raw Materials",
  },
  {
    id: 328,
    parentCategory: 61,
    name: "100% Silk Fabric",
    completeName: "Other Categories > Raw Materials > 100% Silk Fabric",
    parentPath: "Other Categories > Raw Materials",
  },
  {
    id: 329,
    parentCategory: 61,
    name: "100% Polyester Yarn",
    completeName: "Other Categories > Raw Materials > 100% Polyester Yarn",
    parentPath: "Other Categories > Raw Materials",
  },
  {
    id: 330,
    parentCategory: 61,
    name: "Thread",
    completeName: "Other Categories > Raw Materials > Thread",
    parentPath: "Other Categories > Raw Materials",
  },
  {
    id: 331,
    parentCategory: 62,
    name: "Food Cupboards",
    completeName: "Other Categories > Grocery > Food Cupboards",
    parentPath: "Other Categories > Grocery",
  },
  {
    id: 332,
    parentCategory: 62,
    name: "Baby Products",
    completeName: "Other Categories > Grocery > Baby Products",
    parentPath: "Other Categories > Grocery",
  },
  {
    id: 333,
    parentCategory: 62,
    name: "Plastic & Paper Products",
    completeName: "Other Categories > Grocery > Plastic & Paper Products",
    parentPath: "Other Categories > Grocery",
  },
  {
    id: 334,
    parentCategory: 62,
    name: "Drinks",
    completeName: "Other Categories > Grocery > Drinks",
    parentPath: "Other Categories > Grocery",
  },
  {
    id: 335,
    parentCategory: 62,
    name: "Drinks",
    completeName: "Other Categories > Grocery > Drinks",
    parentPath: "Other Categories > Grocery",
  },
  {
    id: 336,
    parentCategory: 62,
    name: "Household Cleaning",
    completeName: "Other Categories > Grocery > Household Cleaning",
    parentPath: "Other Categories > Grocery",
  },
  {
    id: 337,
    parentCategory: 62,
    name: "Beer, Wine & Spirits",
    completeName: "Other Categories > Grocery > Beer, Wine & Spirits",
    parentPath: "Other Categories > Grocery",
  },

  // CATEGORIES STARTS HERE

  // CATEGORIES ENDS HERE
];
